"""add pdf_storage_dir to app_settings

Revision ID: 07d7375b07fc
Revises: bbe4bcaa5a32
Create Date: 2026-07-26 15:26:44.122524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07d7375b07fc'
down_revision: Union[str, Sequence[str], None] = 'bbe4bcaa5a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('pdf_storage_dir', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'pdf_storage_dir')
    # ### end Alembic commands ###
