"""create initial tables

Revision ID: bbe4bcaa5a32
Revises: 
Create Date: 2026-07-25 11:05:40.366913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbe4bcaa5a32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=10), server_default=sa.text("'INV-'"), nullable=True),
    sa.Column('next_invoice_number', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('fname', sa.String(length=50), nullable=True),
    sa.Column('lname', sa.String(length=50), nullable=True),
    sa.Column('addr_line1', sa.String(length=50), nullable=True),
    sa.Column('addr_line2', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('phone_num', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('setup_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('next_invoice_number >= 1', name='next_invoice_number_positive_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(length=150), nullable=True),
    sa.Column('lname', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('setup_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_index(op.f('ix_client_phone'), 'client', ['phone'], unique=False)
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=50), server_default=sa.text("'billing'"), nullable=False),
    sa.Column('addr_line1', sa.String(length=100), nullable=False),
    sa.Column('addr_line2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('setup_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_client_id'), 'address', ['client_id'], unique=False)
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('setup_dt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('issue_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_dt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=10), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default=sa.text('(0.00)'), nullable=False),
    sa.Column('pdf_path', sa.String(length=512), nullable=True),
    sa.Column('bill_to_name', sa.String(length=256), nullable=True),
    sa.Column('bill_to_company', sa.String(length=256), nullable=True),
    sa.Column('bill_to_email', sa.String(length=150), nullable=True),
    sa.Column('bill_to_phone', sa.String(length=20), nullable=True),
    sa.Column('bill_to_addr_line1', sa.String(length=100), nullable=True),
    sa.Column('bill_to_addr_line2', sa.String(length=100), nullable=True),
    sa.Column('bill_to_city', sa.String(length=50), nullable=True),
    sa.Column('bill_to_state', sa.String(length=50), nullable=True),
    sa.Column('bill_to_zip_code', sa.String(length=10), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'sent', 'paid', 'void')", name='status_valid_values_check'),
    sa.CheckConstraint('total >= 0', name='total_nonnegative_check'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_client_id'), 'invoice', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoice_invoice_no'), 'invoice', ['invoice_no'], unique=True)
    op.create_index(op.f('ix_invoice_issue_dt'), 'invoice', ['issue_dt'], unique=False)
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default=sa.text('(0.00)'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position >= 0', name='position_nonnegative_check'),
    sa.CheckConstraint('qty > 0', name='qty_positive_check'),
    sa.CheckConstraint('unit_price >= 0', name='unit_price_nonnegative_check'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_line_item_invoice_id_position', 'line_item', ['invoice_id', 'position'], unique=False)
    op.create_index(op.f('ix_line_item_invoice_id'), 'line_item', ['invoice_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_item_invoice_id'), table_name='line_item')
    op.drop_index('idx_line_item_invoice_id_position', table_name='line_item')
    op.drop_table('line_item')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_issue_dt'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_invoice_no'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_client_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_address_client_id'), table_name='address')
    op.drop_table('address')
    op.drop_index(op.f('ix_client_phone'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
